name: campusmate
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    dropdown_search: ^5.0.6
    firebase_core: ^2.27.1
    firebase_database: ^10.4.10
    mailer: ^6.1.0
    crypto: ^3.0.3
    firebase_auth: ^4.17.9
    firebase: ^9.0.3
    http: ^0.13.6
    excel: ^4.0.3
    cloud_firestore: ^4.15.10
    random_name_generator: ^1.3.0
    flutter_lorem: ^2.0.0
    google_mobile_ads: ^5.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    assets:
        - assets/ # assets 폴더의 모든 이미지를 불러옴
    uses-material-design: true
