// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuxlB4N9MCjNysmn_AeLO7sJ1J829Qnw',
    appId: '1:562921217483:web:208d83220919656bf1ea4e',
    messagingSenderId: '562921217483',
    projectId: 'classmate-81447',
    authDomain: 'classmate-81447.firebaseapp.com',
    storageBucket: 'classmate-81447.appspot.com',
    measurementId: 'G-3RFQ1DM5VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fFbx3eESpr1zCfFjM22JuzUgEn4sppc',
    appId: '1:562921217483:android:4cc0626a33dff246f1ea4e',
    messagingSenderId: '562921217483',
    projectId: 'classmate-81447',
    storageBucket: 'classmate-81447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB62TlOVo77dl2sNPjkEKy_pDyfWgrVffw',
    appId: '1:562921217483:ios:7d3af87da3f08109f1ea4e',
    messagingSenderId: '562921217483',
    projectId: 'classmate-81447',
    storageBucket: 'classmate-81447.appspot.com',
    iosBundleId: 'com.example.campusmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB62TlOVo77dl2sNPjkEKy_pDyfWgrVffw',
    appId: '1:562921217483:ios:4a39e788242afdbff1ea4e',
    messagingSenderId: '562921217483',
    projectId: 'classmate-81447',
    storageBucket: 'classmate-81447.appspot.com',
    iosBundleId: 'com.example.campusmate.RunnerTests',
  );
}
